name: Verification

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  lint: 
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
             
      - name: Run GolangCI-Lint
        uses: Mushus/golangci-linter@v1.1.1
        with:
          config: .golangci.yml

  build:
    name: Run Tests
    needs: [lint]
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run unit test
      run: CGO_ENABLED=1 go test -v -race -cover ./...
